### ISSUE TITLE
Consider using rstrip

### ISSUE THREAD

**Issue by lemire** [McJones/jupyter-swift-kernel#1]
Python has a function to remove all characters from a set at the end of a string: https://www.tutorialspoint.com/python/string_rstrip.htm

**Comment by McJones** [comment]
Yeah I initially used rstrip but unless I misread how to use it, it strips ALL the whitespace including any newlines we might actually want preserved in the output. Let me know if i've got that wrong.

**Comment by lemire** [comment]
Try running this...
https://repl.it/FRMy/0

**Comment by McJones** [comment]
Right-oh, I changed the code in the latest push to use rstrip instead of my hack, thanks for the heads up.
