### ISSUE TITLE
Installing using Docker

### ISSUE THREAD

**Issue by odewahn** [McJones/jupyter-swift-kernel#2]
Hi!  Thanks for this cool project.  I'm trying to create a Docker image for this that has everything set up, but am having trouble getting the kernel itself to run.  First, here's my Dockerfile:

https://github.com/odewahn/swift-kernel-dockerfile/blob/master/Dockerfile

This builds fine and I'm able to run the notebook and see "Swift" in the Kernels dropdown list.  However, then I try to create a notebook with the kernel, I get these errors:

```
[I 00:40:43.923 NotebookApp] Kernel started: f920b2c2-e156-40b0-bc33-22e38606a8dd
/usr/bin/python: No module named swiftkernel
[I 00:40:46.923 NotebookApp] KernelRestarter: restarting kernel (1/5)
/usr/bin/python: No module named swiftkernel
[I 00:40:49.940 NotebookApp] KernelRestarter: restarting kernel (2/5)
/usr/bin/python: No module named swiftkernel
[I 00:40:52.956 NotebookApp] KernelRestarter: restarting kernel (3/5)
/usr/bin/python: No module named swiftkernel
[W 00:40:53.967 NotebookApp] Timeout waiting for kernel_info reply from f920b2c2-e156-40b0-bc33-22e38606a8dd
[I 00:40:55.967 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel f920b2c2-e156-40b0-bc33-22e38606a8dd restarted
/usr/bin/python: No module named swiftkernel
[W 00:40:58.982 NotebookApp] KernelRestarter: restart failed
```

Any thoughts on what might be going on?

Andrew

**Comment by McJones** [comment]
Docker isn't exactly my strongest area but it looks like it's Python that can't find the kernel subclass and not a Jupyter issue.
I had a similar issue on my dev machine and I fixed it by appending the swift kernel install location to the **$PYTHONPATH** shell variable. You should be able to see where Jupiter installed the kernel by running `jupyter kernelspec list`.

From what I can tell about python and Jupiter this shouldn't have been necessary, and in my case I put it down to me being on a Mac (with its dodgy default Python setup) and years of me doing dodgy things to Python... If this fixes it I'll have to try and bring it to the attention of the Jupyter devs as this kernel is based on their example kernel documentation.

**Comment by odewahn** [comment]
Awesome -- adding it to the *$PYTHONPATH* was just what I needed.  Seems to be running fine, now.  Thanks for the pointer!
